[tools]
"cargo:cargo-binstall" = "latest"
"cargo:cargo-workspaces" = "latest"
"cargo:cargo-autoinherit" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-expand" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-toml" = "latest"
just = "latest"
