[package]
name = "cata"
version = "0.1.0"
authors = ["Thomas Rampelberg <thomas@saunter.org>"]
description = "toolkit for building large CLIs"
documentation = "https://docs.rs/cata"
edition = "2021"

[workspace.dependencies]
async-trait = "0.1.81"
clap = { version = "4.5.7", features = ["derive", "env"] }
eyre = "0.6.12"

[dependencies]
async-trait = { workspace = true }
cata-derive = { path = "derive" }
eyre = { workspace = true }
futures = "0.3.30"

[workspace]
members = ["derive", "examples/basic"]
