[package]
name = "cata"
version = "0.1.0"
authors = ["Thomas Rampelberg <thomas@saunter.org>"]
description = "toolkit for building large CLIs"
documentation = "https://docs.rs/cata"
edition = "2021"

[workspace.dependencies]
async-trait = "0.1.81"
clap = { version = "4.5.7", features = ["derive", "env"] }
eyre = "0.6.12"
serde = { version = "1.0.204", features = ["derive"] }
tabled = "0.15.0"
tokio = { version = "1.38.0", features = ["full"] }

[dependencies]
async-trait.workspace = true
cata-derive = { path = "derive" }
clap.workspace = true
eyre.workspace = true
futures = "0.3.30"
serde.workspace = true
serde_json = "1.0.120"
serde_yaml = "0.9.34"
tabled.workspace = true

[workspace]
members = ["derive", "examples/basic", "examples/output"]
