[package]
name = "cata"
version = "0.1.0"
authors = ["Thomas Rampelberg <thomas@saunter.org>"]
description = "toolkit for building large CLIs"
documentation = "https://docs.rs/cata"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
eyre = "0.6.12"
