[package]
name = "example-telemetry"
edition = "2021"
version.workspace = true
authors.workspace = true
documentation.workspace = true
license-file.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
