name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install nightly for rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: justfile
        run: just check
